config/routes.rb
Rails.application.routes.draw do

    devise_for :users, :path => '', :path_names => {:sign_in => '/administrator/login', :sign_out => '/administrator/logout_session'}
    resources :expertises
    resources :contacts

    root 'home#index'
    get '/aboutus' => 'home#about'
    get '/Expertise' => 'home#expertise'
    get '/works' => 'home#work'
    get '/works/arividam' => 'home#arividam'
    get '/works/lms' => 'home#lms'
    get '/works/peecs' => 'home#peecs'
    get '/c4s/contact' => 'home#contact'
    get '/c4s/services' => 'home#services'

    get '/admin/expertise/5624_view' => 'administrator#index'
    get '/admin/contacts/245226_index' => 'administrator#admin_expertise_list'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/expertise.rb
class Expertise < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/administrator_controller.rb
class AdministratorController < ApplicationController

    before_filter :authenticate_user!

    def index
        @data = Contact.all

        render :layout => "layouts/administrator"
    end
    def admin_expertise_list
        
        @expert_list = Expertise.all
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
     #   format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.html { redirect_to '/c4s/contact', notice: 'Contact was successfully created. we will contact you soon' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to admin_expertise_5624_view_path, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :mobile, :subject, :Message)
    end
end

app/controllers/expertises_controller.rb
class ExpertisesController < ApplicationController
  before_action :set_expertise, only: [:show, :edit, :update, :destroy]

  # GET /expertises
  # GET /expertises.json
  def index
    @expertises = Expertise.all
  end

  # GET /expertises/1
  # GET /expertises/1.json
  def show
  end

  # GET /expertises/new
  def new
    @expertise = Expertise.new
  end

  # GET /expertises/1/edit
  def edit
  end

  # POST /expertises
  # POST /expertises.json
  def create
    @expertise = Expertise.new(expertise_params)

    respond_to do |format|
      if @expertise.save
        format.html { redirect_to '/Expertise', notice: 'Request was successfully created.' }
        format.json { render :show, status: :created, location: @expertise }
      else
        format.html { render :new }
        format.json { render json: @expertise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expertises/1
  # PATCH/PUT /expertises/1.json
  def update
    respond_to do |format|
      if @expertise.update(expertise_params)
        format.html { redirect_to @expertise, notice: 'Expertise was successfully updated.' }
        format.json { render :show, status: :ok, location: @expertise }
      else
        format.html { render :edit }
        format.json { render json: @expertise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expertises/1
  # DELETE /expertises/1.json
  def destroy
    @expertise.destroy
    respond_to do |format|
      format.html { redirect_to admin_contacts_245226_index_path, notice: 'Expertise was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expertise
      @expertise = Expertise.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expertise_params
      params.require(:expertise).permit(:name, :email, :subject, :question)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
  def expertise
    @expertise = Expertise.new
  end
  def work
    render :layout => "layouts/leftmenulayout"
  end
  def arividam
    render :layout => "layouts/leftmenulayout"
  end
  def peecs
    render :layout => "layouts/leftmenulayout"
  end
  def lms
    render :layout => "layouts/leftmenulayout"
  end
  def contact
    @contact = Contact.new
  end
end

app/helpers/administrator_helper.rb
module AdministratorHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/expertises_helper.rb
module ExpertisesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/administrator/admin_expertise_list.html.erb
<style>
.glyphicon-lg
{
    font-size:4em
}
.info-block
{
    margin-bottom:25px
}
.info-block .square-box
{
    width:100px;min-height:110px;margin-right:22px;text-align:center!important;padding:20px 0
}
.info-block.block-info:hover
{
    border:1px solid #20819e;
}
.info-block.block-info .square-box
{
    color:#FFF
}
.btn-circle{
    width: 30px;
    height: 30px;
    padding: 3px;
    font-size: 18px;
    line-height: 1.33;
    float:right;
    border-radius: 15px;
}
.txtstyle{
    color:black;
}
.txtmsg{
    color:blue;
}
</style>
<script>
$(function() {    
        $('#input-search').on('keyup', function() {
            var rex = new RegExp($(this).val(), 'i');
            $('.searchable-container .items').hide();
            $('.searchable-container .items').filter(function() {
                return rex.test($(this).text());
                }).show();
            });
        });
</script>

<div class="container">

    <div class="row">
        <h2>Expertise list</h2>
        <div class="col-lg-12">
            <div class="col-md-6">
                <% if notice %>
                    <div data-alert class="alert alert-success">
                    <a href="#" class="close">&times;</a>
                    <%= content_tag :div, notice %>
                </div>
            <% end %>
            </div>

            <input type="search" class="form-control" id="input-search" placeholder="Search contacts..." >
        </div>
        <div class="searchable-container">

            <% @expert_list.each do |list| %>   
                <div class="items col-md-6 clearfix" style="padding:1%;margin-top:1%;">

                <div class="info-block block-info clearfix">
                    <div class="square-box pull-left">
                        <%= link_to 'X', list, method: :delete, data: { confirm:   'Are you sure?' }, type: "button" , class: "btn btn-info btn-cycle" %> 
                    </div>
                    <table>
                        <tr><td>Name : </td><td class="txtstyle"><%= list.name %></td></tr>
                        <tr><td>Email : </td><td class="txtstyle"><%= list.email %></td></tr>
                        <tr><td>Subject : </td><td class="txtstyle"><%= list.subject %></td></tr>
                        <tr><td>Message : </td><td class="txtmsg"><%= list.question %></td></tr>
                        <tr><td>Date</td><td class="txtstyle"><%= list.created_at %></td></tr>
                    </table>
                </div>
            </div>
        <% end %>                 
        </div>
    </div>
</div>

app/views/administrator/index.html.erb
<style>
.glyphicon-lg
{
    font-size:4em
}
.info-block
{
    margin-bottom:25px
}
.info-block .square-box
{
    width:100px;min-height:110px;margin-right:22px;text-align:center!important;padding:20px 0
}
.info-block.block-info:hover
{
    border:1px solid #20819e;
}
.info-block.block-info .square-box
{
    color:#FFF
}
.btn-circle{
    width: 30px;
    height: 30px;
    padding: 3px;
    font-size: 18px;
    line-height: 1.33;
    float:right;
    border-radius: 15px;
}
.txtstyle{
    color:black;
}
.txtmsg{
    color:blue;
}
</style>
<script>
$(function() {    
        $('#input-search').on('keyup', function() {
            var rex = new RegExp($(this).val(), 'i');
            $('.searchable-container .items').hide();
            $('.searchable-container .items').filter(function() {
                return rex.test($(this).text());
                }).show();
            });
        });
</script>
<div class="container">
    <div class="row">
        <h2>Contact list</h2>
        <div class="col-lg-12">
            <div class="col-md-6">
                <% if notice %>
                    <div data-alert class="alert alert-success">
                    <a href="#" class="close">&times;</a>
                    <%= content_tag :div, notice %>
                </div>
            <% end %>
            </div>
            <input type="search" class="form-control" id="input-search" placeholder="Search contacts..." >
        </div>
        <div class="searchable-container">

            <% @data.each do |data| %>   
                <div class="items col-md-6 clearfix" style="padding:1%;margin-top:1%;">
                <div class="info-block block-info clearfix">
                    <div class="square-box pull-left">
                        <%= link_to 'X', data, method: :delete, data: { confirm:   'Are you sure?' }, type: "button" , class: "btn btn-info btn-cycle" %>
                    </div>
                    <table>
                        <tr><td>Name : </td><td class="txtstyle"><%= data.name %></td></tr>
                        <tr><td>Phone : </td><td class="txtstyle" ><%= data.mobile %>></td></tr>
                        <tr><td>Email : </td><td class="txtstyle"><%= data.email %></td></tr>
                        <tr><td>Subject : </td><td class="txtstyle"><%= data.subject %></td></tr>
                        <tr><td>Message : </td><td class="txtmsg"><%= data.Message %></td></tr>
                        <tr><td>Date</td><td class="txtstyle"><%= data.created_at %></td></tr>
                    </table>
                </div>
            </div>
        <% end %>                 
        </div>
    </div>
</div>

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name , class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email , class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :mobile %><br>
    <%= f.text_field :mobile , class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_area :subject , class: 'form-control', rows: '1' %>
  </div>
  <div class="field">
    <%= f.label :Message %><br>
    <%= f.text_area :Message , class: 'form-control',rows: '7' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Listing contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Mobile</th>
      <th>Subject</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.mobile %></td>
        <td><%= contact.subject %></td>
        <td><%= contact.Message %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @contact.mobile %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @contact.subject %>
</p>

<p>
  <strong>Message:</strong>
  <%= @contact.Message %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/expertises/_form.html.erb
<%= form_for(@expertise) do |f| %>
  <% if @expertise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expertise.errors.count, "error") %> prohibited this expertise from being saved:</h2>

      <ul>
      <% @expertise.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email , class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_area :subject , class: 'form-control' , rows:1 %>
  </div>
  <div class="field">
    <%= f.label :question %><br>
    <%= f.text_area :question , class: 'form-control', rows:10 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/expertises/edit.html.erb
<h1>Editing expertise</h1>

<%= render 'form' %>

<%= link_to 'Show', @expertise %> |
<%= link_to 'Back', expertises_path %>

app/views/expertises/index.html.erb
<h1>Listing expertises</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Subject</th>
      <th>Question</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @expertises.each do |expertise| %>
      <tr>
        <td><%= expertise.name %></td>
        <td><%= expertise.email %></td>
        <td><%= expertise.subject %></td>
        <td><%= expertise.question %></td>
        <td><%= link_to 'Show', expertise %></td>
        <td><%= link_to 'Edit', edit_expertise_path(expertise) %></td>
        <td><%= link_to 'Destroy', expertise, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Expertise', new_expertise_path %>

app/views/expertises/new.html.erb
<h1>New expertise</h1>

<%= render 'form' %>

<%= link_to 'Back', expertises_path %>

app/views/expertises/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @expertise.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @expertise.email %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @expertise.subject %>
</p>

<p>
  <strong>Question:</strong>
  <%= @expertise.question %>
</p>

<%= link_to 'Edit', edit_expertise_path(@expertise) %> |
<%= link_to 'Back', expertises_path %>

app/views/home/about.html.erb
<div class="col-md-12 box-green txtpadd whitetext" style="margin-top:-20px;">
  <div class="container">
    <div class="col-md-6">
      <h3>ABOUT US</h3>
      <p>WHAT WE ARE</p>
    </div>
    <div class="col-md-6">
      <ul class="breadcrumb pull-right">
        <li class="active">About Us</li>
      </ul>
    </div>
  </div>
</div>
<div class="col-md-12">
  <div class="container" style="padding:5%">
    <h4>CENTER FOR SOCIAL COMPUTING</h4>
    <hr/>
    <p>Centre for Social Computing &amp; Information Society, a Wayanad based ICT organization was
    registered under the ‘Societies Registration Act XXII of 1860’. As a Government accredited ICT
    organization in Kerala, Centre for Social Computing &amp; Information Society (Hereinafter called
    ‘C4S’) have conceptualized, designed, developed and delivered number of social software
    applications and platforms for agriculture, health, education and community empowerment
    projects of various government agencies including NIC, Kerala State Planning Board, Kerala
    State IT Mission ,Local self-governance department, General Education Department. C4S is
    also an Independent Research &amp; Development Agency in ICT4D (Information Communication
    Technology for Development) domain dedicated to find solutions to bridge the digital divide and
    to uplift the downtrodden and to create economic and commercial viability using ICT as means.</p>
  </div>
</div>

app/views/home/arividam.html.erb
<h3>Arividam</h3>
<p>Arividam engineering entrance coaching scheme, 
is a government project,keralas biggest database record of 10lakhs 
users The Public Entrance Examination Coaching Scheme (PEECS) of the Government of Kerala . 
The innovative project of the Higher Education department, aimed at giving free coaching to Higher
 Secondary students of the state, both in the Government and Aided sector, public engineering entrance coaching scheme, 
is a government project,keralas biggest database record of 10lakhs 
users The Public Entrance Examination Coaching Scheme (PEECS) of the Government of Kerala . 
The innovative project of the Higher Education department, aimed at giving free coaching to Higher
 Secondary students of the state, both in the Government and Aided sector, public engineering entrance coaching scheme, 
is a government project,keralas biggest database record of 10lakhs 
users The Public Entrance Examination Coaching Scheme (PEECS) of the Government of Kerala . 
The innovative project of the Higher Education department, aimed at giving free coaching to Higher
 Secondary students of the state, both in the Government and Aided sector,</p>

app/views/home/contact.html.erb
<div class="col-md-12 box-green txtpadd whitetext" style="margin-top:-20px;">
  <div class="container">
    <div class="col-md-6">
      <h3>CONTACT US</h3>
      <p>CONTACT FORM</p>
    </div>
    <div class="col-md-6">
      <ul class="breadcrumb pull-right">
        <li class="active">c4s / contacts</li>
      </ul>
    </div>
  </div>
</div>
<div class="col-md-12">
  <div class="container" style="padding:5%">
    <div class="col-md-7" style="margin-bottom:5%;padding:0px 4% 0px 0px">
      <% if notice %>
            <div data-alert class="alert alert-success">
            <a href="#" class="close">&times;</a>
            <%= content_tag :div, notice %>
          </div>
        <% end %>
      <%= render "contacts/form" %>
    </div>
    <div class="col-md-5 bluebg api_division">
      <h3>Contact info</h3>
      <br/>
      <div class="col-md-12" style="background:white">
          <iframe width:100% frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.com/maps?ie=UTF8&amp;ll=11.665686,76.250696&amp;spn=0.012819,0.019741&amp;t=m&amp;z=16&amp;output=embed"></iframe><br /><small><a href="https://www.google.com/maps?ie=UTF8&amp;ll=11.665686,76.250696&amp;spn=0.012819,0.019741&amp;t=m&amp;z=16&amp;source=embed" style="color:#0000FF;text-align:left">View Larger Map</a></small>
      </div>
      <div class="col-md-12">
        <h4> Centre for social computing & <br/>Information Society </h4>
        <h5> Cyber park,Sulthan Bathery,</h5><h5>Wayanad - 673592 </h5>
      </div>
    </div>
  </div>
</div>

app/views/home/expertise.html.erb
<div class="col-md-12 box-green txtpadd whitetext" style="margin-top:-20px;">
  <div class="container">
    <div class="col-md-6">
      <h3>EXPERTISE</h3>
      <p>WHAT WANT TO KNOW FROM US</p>
    </div>
    <div class="col-md-6">
      <ul class="breadcrumb pull-right">
        <li class="active">Expertise</li>
      </ul>
    </div>
  </div>
</div>
<div class="col-md-12">
  <div class="container" style="padding:5%">

    <div class="col-md-2">
    </div>
    <div class="col-md-8">
      <%= image_tag("talk.png", class:'logowidth' ) %>
    </div>
    <div class="col-md-2">
    </div>
  </div>
    <div class="container">
      <div class="col-md-3">
      </div>
      <div class="col-md-6">
        <% if notice %>
              <div data-alert class="alert alert-success">
              <a href="#" class="close">&times;</a>
              <%= content_tag :div, notice %>
            </div>
          <% end %>
        <%= render "expertises/form" %>
      </div>
      <div class="col-md-3">
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="col-md-12">
    <div class="container">
        <div class="col-md-8" style="margin-bottom:15px;">
            <%= image_tag("keyfine2.png", onmouseover: "this.src='#{asset_path('keyfine1.png')}'", :class => "thnkman", onmouseout: "this.src='#{asset_path('keyfine2.png')}'")%>
        </div>
        <div class="col-md-4">
            <div id="myCarousel" class="carousel slide">
                <div class="carousel-inner">
                    <div class="item active" style="background:#34495E;padding:1%;color:white;">
                        <blockquote>
                            <%= image_tag("logotrial.png",:class => "logowidth") %>

                            <p>The center for social computing and information society is an ICT organization</p>
                        </blockquote>
                    </div>
                    <div class="item box-green">
                        <blockquote>
                            <p>we design and develop autonomic open source ICT solutions across the social sector to bridge the gap between digital haves and have nots the social sector to bridge the gap between digital haves and have nots in under connected information republics</p>
                        </blockquote>
                    </div>
                    <div class="item box-green">
                        <blockquote>
                            <p>Hackdom is an ICT service modeling and project formulation lab working in C4S. Everybody can come here and talk to our developers and practitioners for a new solution in any area of ICT.Hackdom has A(ndroid) to Z(ystem) resources and developing solutions</p>
                        </blockquote>
                    </div>
                </div>
                <div class="carousel-controls">
                    <a class="carousel-control left" href="#myCarousel" data-slide="prev"> < </a>
                    <a class="carousel-control right" href="#myCarousel" data-slide="next"> > </a>
                </div>
            </div><!-- End Carousel -->
        </div>
    </div>
</div>
<div class="col-md-12" style="margin:5% 0px 5% 0px;">
    <div class="container">
        <div class="row nav-row">
            <div class="col-md-2">
                <%= image_tag("glyfy/eye.png") %>
                <p>Software development</p>
            </div>
            <div class="col-md-2 active">
                <%= image_tag("glyfy/wifidevice.png") %>
                <p>Wide wifi</p>
            </div>
            <div class="col-md-2">
                <%= image_tag("glyfy/report.png") %>
                <p>Big data</p>
            </div>
            <div class="col-md-2">
                <%= image_tag("glyfy/msg.png") %>
                <p>Collaborative</p>
            </div>
            <div class="col-md-2">
                <%= image_tag("glyfy/android.png") %>
                <p>Mobile Apps</p>
            </div>
            <div class="col-md-2">
                <%= image_tag("glyfy/support.png") %>
                <p>24 x 7 support</p>
            </div>
        </div>
    </div>
</div>
<div class="col-md-12">
    <div class="container">
        <div class="col-md-4 txtcntr txtpadd">
            <h4>L system of e-ducation</h4>
            <h6>The 'biggest' LMS in India with 4 lakh users</h6>
            <p class="txtpadd txtjustfy">'L' is an intellectually conceived, pedagogically designed, dynamically coded and massively used learning management system with web 2 features for all kind of academic and training institutions. The prestigious public entrance coaching scheme -www.peecs.kerala.gov.in -of Kerala government has adapted the ‘L’ software system developed by C4S for their e-learning portal to deliver personalized entrance coaching content to all higher secondary school students of Kerala. Beyond the 'usual apps’ of an LMS ,the ‘L’ system has unique capabilities on which the gamification of learning environment is deeply customizable in a content-wise manner and other tutor-admin environments are appy than any other systems in the LMS world.The ‘L’ system has android,web and wireless community forms on which resource hungry apps are waiting for communities to come on line in their own line.</p>
        </div>

        <div class="col-md-4 txtcntr txtpadd">
            <h4>Wayanad Wide Wifi</h4>
            <h6>The first rural wireless community in India</h6>
            <p class="txtpadd txtjustfy">You are knowing now about a revolutionary rural connectivity on open radio implemented in Wayanad , a remote district of Kerala, southern state of India.The growing wayanad wide wi fi has connected many remote villages to 80 km away hospital, university and other knowledge institutions with 100 Mbps speed.The low cost - high speed wireless network has covered 2131 km2 area of Wayanad region on which doctors,educators, agri scientists, trainers and other experts are doing their job for 36 villages and different communities in the villages are interacting with the expert community. The C4S has designed and deployed wayanad wide wireless network in cooperation with governmental and non-governmental agencies.We are building a rural ,free ,autonomic wireless community network of farmers, women, students, activists, academicians, development practitioners, subject matter experts, tribal people, educators and you!Join us to connect you ,your content and your community.</p>
        </div>
        <div class="col-md-4 txtcntr txtpadd">
            <h4>hacKdom</h4>
            <h6>Problem meets Solution</h6>
            <p class="txtpadd txtjustfy">Hackdom is an ICT service modeling and project formulation lab working in C4S Cyber Reserve campus in which people practicing theories and theorising practices.Everybody can come here and talk to our developers and practitioners for a new solution in any area of ICT.Hackdom has A(ndroid) to Z(ystem) resources and developing solutions for many e-governance projects to democratize ICT and conducting ‘digital dissidence workshop’ for journalists and activists to fight for the techno-political issues like ‘net neutrality’rak.</p>
        </div>
    </div>
</div>

app/views/home/lms.html.erb
<h3>LMS</h3>
<p>Arividam engineering entrance coaching scheme, 
is a government project,keralas biggest database record of 10lakhs 
users The Public Entrance Examination Coaching Scheme (PEECS) of the Government of Kerala . 
The innovative project of the Higher Education department, aimed at giving free coaching to Higher
 Secondary students of the state, both in the Government and Aided sector, public engineering entrance coaching scheme, 
is a government project,keralas biggest database record of 10lakhs 
users The Public Entrance Examination Coaching Scheme (PEECS) of the Government of Kerala . 
The innovative project of the Higher Education department, aimed at giving free coaching to Higher
 Secondary students of the state, both in the Government and Aided sector, public engineering entrance coaching scheme, 
is a government project,keralas biggest database record of 10lakhs 
users The Public Entrance Examination Coaching Scheme (PEECS) of the Government of Kerala . 
The innovative project of the Higher Education department, aimed at giving free coaching to Higher
 Secondary students of the state, both in the Government and Aided sector,</p>